# Generated by Django 4.0.4 on 2022-06-26 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalhes_Imovel',
            fields=[
                ('ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('NOME', models.CharField(max_length=200, verbose_name='Nome do detalhe')),
                ('SITUACAO', models.CharField(choices=[('NOVO', 'Imóvel novo'), ('USADO', 'Imóvel usado')], max_length=5, verbose_name='Situação:')),
                ('TIPO', models.CharField(choices=[('RES', 'Casa Residencial'), ('APE', 'Apartamento')], max_length=3, verbose_name='Tipo Imóvel:')),
                ('TIPO_CONDOMINIO', models.CharField(choices=[('FECHADO', 'Condominio Fechado'), ('ABERTO', 'Condominio Aberto')], max_length=7, verbose_name='Tipo do Condominio:')),
                ('AREA_UTIL', models.IntegerField(verbose_name='Metros quadrados da área util:')),
                ('AREA_TOTAL', models.IntegerField(verbose_name='Metros quadrados da área total:')),
                ('CREATED', models.DateTimeField(auto_now_add=True, verbose_name='Adicionou:')),
                ('EDIT', models.DateTimeField(auto_now=True, verbose_name='Editou:')),
                ('USERCAD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Detalhes dos Imóveis',
                'db_table': 'IMOVEL_DETALHES',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RUA', models.CharField(max_length=200, verbose_name='Rua:')),
                ('NUMERO', models.IntegerField(verbose_name='Numero da casa:')),
                ('COMPLEMENTO', models.CharField(max_length=200, verbose_name='Complemento')),
                ('CEP', models.CharField(max_length=8, verbose_name='Cep:')),
                ('BAIRRO', models.CharField(max_length=50, verbose_name='Bairro:')),
                ('CIDADE', models.CharField(max_length=50, verbose_name='Cidade:')),
                ('ESTADO', models.CharField(choices=[('RS', 'Rio Grande do Sul')], max_length=2, verbose_name='Estado:')),
                ('CREATED', models.DateTimeField(auto_now_add=True, verbose_name='Adicionou:')),
                ('EDIT', models.DateTimeField(auto_now=True, verbose_name='Editou:')),
                ('USERCAD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Endereços',
                'db_table': 'ENDERECOS',
            },
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('SLUG', models.CharField(max_length=255, unique=True, verbose_name='Slug:')),
                ('NOME_IMOVEL', models.CharField(max_length=255, verbose_name='Nome do imóvel:')),
                ('DATA_IMOVEL', models.DateField(verbose_name='Data do imóvel:')),
                ('IMAGEM_PRINCIPAL', models.ImageField(upload_to='')),
                ('DESCRICAO', models.TextField(verbose_name='Descrição:')),
                ('NUMERO_QUARTOS', models.IntegerField(verbose_name='Numero de quartos:')),
                ('NUMERO_BANHEIROS', models.IntegerField(verbose_name='Numero de banheiros:')),
                ('GARAGEM', models.IntegerField(verbose_name='Quantidade de espaço na garagem:')),
                ('CREATED', models.DateTimeField(auto_now_add=True, verbose_name='Adicionou:')),
                ('EDIT', models.DateTimeField(auto_now=True, verbose_name='Editou:')),
                ('ENDERECO', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.endereco')),
                ('USERCAD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lista de Imóveis',
                'db_table': 'IMOVEIS',
                'ordering': ('-CREATED',),
            },
        ),
        migrations.CreateModel(
            name='Inquilino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOME', models.CharField(max_length=100, verbose_name='Nome:')),
                ('EMAIL', models.EmailField(max_length=254, verbose_name='Email:')),
                ('TELEFONE', models.CharField(max_length=100, verbose_name='Telefone:')),
                ('CPF', models.CharField(max_length=11, verbose_name='CPF:')),
                ('RG', models.CharField(max_length=10, verbose_name='RG:')),
                ('DATA_NASCIMENTO', models.DateField(verbose_name='Data Nascimento:')),
                ('PROFISSAO', models.CharField(max_length=50, verbose_name='Profissão:')),
                ('SEXO', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Nenhuma das opções')], max_length=1, verbose_name='Sexo:')),
                ('CREATED', models.DateTimeField(auto_now_add=True, verbose_name='Adicionou:')),
                ('EDIT', models.DateTimeField(auto_now=True, verbose_name='Editou:')),
                ('ENDERECO', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.endereco')),
                ('IMOVEL', models.ManyToManyField(to='sistema.imovel')),
                ('USERCAD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lista de Inquilinos',
                'db_table': 'INQUILINOS',
            },
        ),
        migrations.CreateModel(
            name='Imovel_Detalhes_Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_DETALHES_IMOVEL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.detalhes_imovel')),
                ('ID_IMOVEL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.imovel')),
            ],
            options={
                'verbose_name_plural': 'Detalhes dos Imoveis com o Imovel',
                'db_table': 'IMOVEL_DETALHES_IMOVEL',
            },
        ),
        migrations.CreateModel(
            name='GastosInquilino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LUZ', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Conta de Luz:')),
                ('AGUA', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Conta de Água:')),
                ('INTERNET', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Conta de Internet:')),
                ('TELEFONE', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Conta de Telefone:')),
                ('MERCADO', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Gastos com Mercado:')),
                ('GASTOS_EXTRAS', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Gastos Extras:')),
                ('CREATED', models.DateTimeField(auto_now_add=True, verbose_name='Adicionou:')),
                ('EDIT', models.DateTimeField(auto_now=True, verbose_name='Editou:')),
                ('INQUILINO', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.inquilino')),
                ('USERCAD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lista de Gastos dos Inquilinos',
                'db_table': 'GASTOS_INQULINO',
                'ordering': ('-CREATED',),
            },
        ),
        migrations.CreateModel(
            name='Comodidades_Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VALOR', models.CharField(max_length=255, verbose_name='Digite a comodidade do imovel:')),
                ('CREATED', models.DateTimeField(auto_now_add=True, verbose_name='Adicionou:')),
                ('EDIT', models.DateTimeField(auto_now=True, verbose_name='Editou:')),
                ('IMOVEL_PERTENCENTE', models.ManyToManyField(to='sistema.imovel')),
            ],
            options={
                'verbose_name_plural': 'comodidades dos imóveis',
                'db_table': 'IMOVEIS_COMODIDADES',
            },
        ),
    ]
