# Generated by Django 4.0.5 on 2022-06-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_alter_comodidades_imovel_valor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='TIPO_VENDA',
            field=models.CharField(choices=[('A_VENDA', 'A venda'), ('N_VENDA', 'Não está a venda')], default=None, max_length=7, verbose_name='Tipo do Condominio:'),
            preserve_default=False,
        ),
    ]
