# Generated by Django 4.0.5 on 2022-06-30 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sistema.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sistema', '0003_imovel_tipo_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastosinquilino',
            name='AGUA',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[sistema.validators.valida_limite], verbose_name='Conta de Água:'),
        ),
        migrations.AlterField(
            model_name='gastosinquilino',
            name='LUZ',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[sistema.validators.valida_limite], verbose_name='Conta de Luz:'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='TIPO_VENDA',
            field=models.CharField(choices=[('A_VENDA', 'A venda'), ('N_VENDA', 'Não está a venda')], max_length=7, verbose_name='Situação:'),
        ),
        migrations.CreateModel(
            name='ContaBancariaImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VALOR', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Conta Bancaria:')),
                ('IPTU', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Iptu:')),
                ('CREATED', models.DateTimeField(auto_now_add=True, verbose_name='Adicionou:')),
                ('EDIT', models.DateTimeField(auto_now=True, verbose_name='Editou:')),
                ('IMOVEL', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.imovel')),
                ('USERCAD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Conta Bancaria do Imovel',
                'db_table': 'CONTA_BANCARIA_IMOVEL',
                'ordering': ('-CREATED',),
            },
        ),
    ]
