# Generated by Django 4.0.5 on 2022-06-30 05:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_alter_gastosinquilino_agua_alter_gastosinquilino_luz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contabancariaimovel',
            name='CONDOMINIO',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8, validators=[django.core.validators.RegexValidator('^[0,1,2,3,4,5,6,7,8,9]', 'O campo deve conter apenas numeros')], verbose_name='Condominio:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contabancariaimovel',
            name='GARAGEM',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8, validators=[django.core.validators.RegexValidator('^[0,1,2,3,4,5,6,7,8,9]', 'O campo deve conter apenas numeros')], verbose_name='Garagem:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imovel',
            name='VALOR_IMOVEL',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12, validators=[django.core.validators.RegexValidator('^[0,1,2,3,4,5,6,7,8,9]', 'O campo deve conter apenas numeros')], verbose_name='Valor do Imovel:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contabancariaimovel',
            name='IPTU',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.RegexValidator('^[0,1,2,3,4,5,6,7,8,9]', 'O campo deve conter apenas numeros')], verbose_name='Iptu:'),
        ),
        migrations.AlterField(
            model_name='gastosinquilino',
            name='GASTOS_EXTRAS',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.RegexValidator('^[0,1,2,3,4,5,6,7,8,9]', 'O campo deve conter apenas numeros')], verbose_name='Gastos Extras:'),
        ),
        migrations.AlterField(
            model_name='gastosinquilino',
            name='INTERNET',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.RegexValidator('^[0,1,2,3,4,5,6,7,8,9]', 'O campo deve conter apenas numeros')], verbose_name='Conta de Internet:'),
        ),
        migrations.AlterField(
            model_name='gastosinquilino',
            name='MERCADO',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.RegexValidator('^[0,1,2,3,4,5,6,7,8,9]', 'O campo deve conter apenas numeros')], verbose_name='Gastos com Mercado:'),
        ),
        migrations.AlterField(
            model_name='gastosinquilino',
            name='TELEFONE',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.RegexValidator('^[0,1,2,3,4,5,6,7,8,9]', 'O campo deve conter apenas numeros')], verbose_name='Conta de Telefone:'),
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='TELEFONE',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^[0,1,2,3,4,5,6,7,8,9]', 'O campo deve conter apenas numeros')], verbose_name='Telefone:'),
        ),
    ]
